name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 0 * * *'  # Se ejecuta una vez al día (a medianoche UTC)
  workflow_dispatch:  # Permite ejecutarlo manualmente cuando quieras

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the fork
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Add upstream repository
        run: |
          git remote add upstream https://github.com/solnou/SdC-Cyber-Core.git
          git fetch upstream
          git checkout main
          git merge upstream/main
          git push origin main
