name: Sync Fork with Upstream

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Add upstream repository (if not exists)
      run: |
        git remote | grep upstream || git remote add upstream https://github.com/solnou/SdC-Cyber-Core.git
        git fetch upstream

    - name: Merge upstream changes into local branch
      run: |
        git checkout main
        git merge upstream/main

    - name: Push changes to origin
      run: |
        git push origin main
